# Application
spring.application.name=secureauth
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/secureauth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380

# JWT
app.jwt.secret=secureauth-super-secret-key-enterprise-identity-service-2024-talha
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Rate Limiting
app.rate-limit.max-attempts=5
app.rate-limit.window-minutes=15
app.rate-limit.lockout-minutes=30

# Account Security
app.security.max-failed-attempts=5
app.security.lockout-duration-minutes=30
app.security.password-reset-expiry-minutes=15

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.secureauth=DEBUG
logging.level.org.springframework.security=INFO